import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import GradientBackground from '@/components/ui/gradient-background';
import { Toaster } from 'sonner';
import { ContextMenu, ContextMenuTrigger } from '@/components/ui/context-menu';
import { ThemeProvider } from '@/components/theme-provider';
import ThemeSwitcher from '@/components/theme-switcher';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider>
          <ContextMenu>
            <ContextMenuTrigger>
              <div className="relative min-h-screen w-full">
                <GradientBackground />
                <main className="relative z-10 w-full lg:mx-auto lg:max-w-7xl">
                  {children}
                </main>
                <Toaster />
                <ThemeSwitcher />
              </div>
            </ContextMenuTrigger>
          </ContextMenu>
        </ThemeProvider>
      </body>
    </html>
  );
}
