import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import Footer from '@/components/footer';
import GradientBackground from '@/components/ui/gradient-background';
import { Toaster } from 'sonner';
import { ContextMenu, ContextMenuTrigger } from '@/components/ui/context-menu';
import { ThemeProvider } from '@/components/theme-provider';
import ThemeSwitcher from '@/components/theme-switcher';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider>
          <ContextMenu>
            <ContextMenuTrigger>
              <div className="relative min-h-screen w-full">
                <GradientBackground />
                <main className="relative z-10 w-full lg:mx-auto lg:max-w-7xl">
                  <NextIntlClientProvider>{children}</NextIntlClientProvider>
                  <Footer />
                </main>
                <Toaster />
                <ThemeSwitcher />
                {/* <MenuButton /> */}
              </div>
            </ContextMenuTrigger>
            {/* <ContextMenuContent className='lg:w-xs'> */}
            {/*   <ContextMenuItem asChild className='py-2'> */}
            {/*     <Link href="/recipes"> */}
            {/*       <span className="text-secondary-foreground text-nowrap">Explore Recipes</span> */}
            {/*     </Link> */}
            {/*   </ContextMenuItem> */}
            {/* </ContextMenuContent> */}
          </ContextMenu>
        </ThemeProvider>
      </body>
    </html>
  );
}
