import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer';
import ThemeSwitcher from '@/components/theme-switcher';
import { ThemeProvider } from 'next-themes';
import GradientBackground from '@/components/ui/gradient-background';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem enableColorScheme>
          <div className="relative min-h-screen w-full">
            <GradientBackground />
            <main className="relative z-10 w-full lg:mx-auto lg:max-w-7xl">
              {children}
              <Footer />
            </main>
            <Toaster />
            <ThemeSwitcher />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
