import type { Metadata } from 'next';
import '@/app/globals.css';
import GradientBackground from '@/components/ui/gradient-background';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-transparent">
      <div>
        {children}
      </div>
    </main>
  )
}
