import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import GradientBackground from '@/components/ui/gradient-background';
import { Toaster } from 'sonner';
import { ContextMenu, ContextMenuTrigger } from '@/components/ui/context-menu';
import { ThemeProvider } from '@/components/theme-provider';
import ThemeSwitcher from '@/components/theme-switcher';
import DashboardSidebar from '@/components/dashboard/left-side-bar';
import DashboardRightSideBar from '@/components/dashboard/right-side-bar';
import DashboardHeader from '@/components/dashboard/header-card';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider>
          <ContextMenu>
            <ContextMenuTrigger>
              <div className="relative min-h-screen w-full">
                <GradientBackground />
                <main className="relative w-full z-10 p-6 grid grid-cols-12 gap-6">
                  <DashboardSidebar />
                  <div className='space-y-8 col-span-8'>
                    <DashboardHeader />
                    {children}
                  </div>
                  <DashboardRightSideBar />
                </main>
                <Toaster />
                <ThemeSwitcher />
              </div>
            </ContextMenuTrigger>
          </ContextMenu>
        </ThemeProvider>
      </body>
    </html>
  );
}
